server:
  port: 9004

spring:
  application:
    name: order-service

  config:
    import: nacos:${spring.application.name}.yml

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: et2601
      config:
        namespace: et2601

